version: "3"
services:
  postgres:
    container_name: eventually-postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - .postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  dynamodb:
    container_name: eventually-dynamodb
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8000:8000"
