@host = http://localhost:3000
###

GET {{host}}/stats
###

GET {{host}}/calculator

GET {{host}}/calculator/calc1
###
GET {{host}}/calculator/calc1/stream
###


GET {{host}}/counter/Counter-Calculator-calc1
###
GET {{host}}/counter/Counter-Calculator-calc1/stream
###

POST {{host}}/calculator/calc1/press-key
Content-Type: application/json

{
  "key": "1"
}

###

POST {{host}}/press-key-adapter
Content-Type: application/json

{
  "id": "calc2",
  "key": "2"
}

###

POST {{host}}/calculator/calc1/press-key
Content-Type: application/json

{ "key": "+" }

###

POST {{host}}/calculator/calc1/press-key
Content-Type: application/json

{ "key" : "=" }

### 

GET {{host}}/calculator/calc1
###
POST {{host}}/counter
Content-Type: application/json

{
  "id": 1,
  "stream": "Calculatorcalc1",
  "version": 44,
  "created": "2020-10-10",
  "name": "DigitPressed",
  "data": { "digit": "1" }
}
