@host = http://localhost:3000
###

GET {{host}}/calculator/calc1
###
GET {{host}}/calculator/calc1/stream
###


GET {{host}}/counter/CounterCalculatorcalc1
###
GET {{host}}/counter/CounterCalculatorcalc1/stream
###

POST {{host}}/calculator/calc1/press-key
Content-Type: application/json

{
  "key": "1"
}

###

POST {{host}}/calculator/calc1/press-key
Content-Type: application/json

{ "key": "+" }

###

POST {{host}}/calculator/calc1/press-key
Content-Type: application/json

{ "key" : "=" }

### 
POST {{host}}/counter/digit-pressed
Content-Type: application/json

{
  "id": 1,
  "stream": "calc2",
  "version": "0",
  "created": "2020-10-10",
  "name": "DigitPressed",
  "data": { "digit": "1" }
}
