GET http://localhost:3000/calculator/calc1
###
GET http://localhost:3000/calculator/calc1/stream
###

POST http://localhost:3000/calculator/calc1/press-key
Content-Type: application/json

{
  "name": "PressKey",
  "data": { "key": "1" }
}

###

POST http://localhost:3000/calculator/calc1/press-key
Content-Type: application/json

{
  "name": "PressKey",
  "data": { "key": "+" }
}

###

POST http://localhost:3000/calculator/calc1/press-key
Content-Type: application/json

{
  "name": "PressKey",
  "data": { "key" : "=" }
}

### 
POST http://localhost:3000/counter/digit-pressed
Content-Type: application/json

{
  "id": "test",
  "version": "0",
  "timestamp": "2021-09-19T23:04:11.309Z",
  "name": "DigitPressed",
  "data": { "digit": "1" }
}