POST http://localhost:3000/counter/digit-pressed
Content-Type: application/json

{
  "eventId": 1,
  "aggregateId": "calc2",
  "aggregateVersion": "0",
  "createdAt": "2020-10-10",
  "name": "DigitPressed",
  "data": { "digit": "1" }
}

###

POST http://localhost:3000/counter/digit-pressed
Content-Type: application/json

{
  "eventId": 1,
  "aggregateId": "calc3",
  "aggregateVersion": "0",
  "createdAt": "2020-10-10",
  "name": "DigitPressed",
  "data": { "digit": "3" }
}

###

POST http://localhost:3000/counter/dot-pressed
Content-Type: application/json

{
  "eventId": 1,
  "aggregateId": "calc2",
  "aggregateVersion": "0",
  "createdAt": "2020-10-10",
  "name": "DotPressed"
}