@host = http://localhost:3000
###

POST {{host}}/counter
Content-Type: application/json

{
  "id": 1,
  "stream": "calc2",
  "version": "0",
  "created": "2020-10-10",
  "name": "DigitPressed",
  "data": { "digit": "1" }
}

###

POST {{host}}/counter
Content-Type: application/json

{
  "id": 1,
  "stream": "calc3",
  "version": "0",
  "created": "2020-10-10",
  "name": "DigitPressed",
  "data": { "digit": "3" }
}

###

POST {{host}}/counter
Content-Type: application/json

{
  "id": 1,
  "stream": "calc2",
  "version": "0",
  "created": "2020-10-10",
  "name": "DotPressed"
}