@host = http://localhost:3000
###

GET {{host}}/stream?limit=100 HTTP/1.1
###
GET {{host}}/stream?after=10
###
GET {{host}}/stream?after=10&limit=3 
###
GET {{host}}/stream/DigitPressed?limit=2 
###
GET {{host}}/stream/OperatorPressed?after=2&limit=5 