@host = http://localhost:3000
###

GET {{host}}/all?limit=100 HTTP/1.1
###
GET {{host}}/all?after=10
###
GET {{host}}/all?after=10&limit=3 
###
GET {{host}}/all?name=DigitPressed&limit=2 
###
GET {{host}}/all?name=OperatorPressed&after=2&limit=5 