
@host = http://localhost:3000
###

GET {{host}}/stream?limit=100
###

POST {{host}}/integrate-account1/account-created
Content-Type: application/json

{
  "name": "AccountCreated",
  "id": 1,
  "stream": "stream",
  "version": "1",
  "created": "2021-12-01",
  "data": { 
    "id": "account-1"
  }
}
###

POST {{host}}/integrate-account2/account-created
Content-Type: application/json

{
  "name": "AccountCreated",
  "id": 1,
  "stream": "stream",
  "version": "1",
  "created": "2021-12-01",
  "data": { 
    "id": "account-1"
  }
}
 