name: CD
on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: yarn install
      - run: yarn build

      - name: semantic release
        run: yarn release
