name: CI-CD
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GIT_USERNAME: rotorsoft
  GIT_USEREMAIL: rotorsoft@outlook.com
  GIT_HOST: github.com
  GIT_REPO: rotorsoft/eventually-monorepo

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_PASSWORD: postgres
        # health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: build service
        run: yarn install && yarn build

      - name: unit test
        run: yarn test --coverage
        env:
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_DATABASE: postgres

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  cd:
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      matrix:
        lib:
          - eventually
          - eventually-pg
          - eventually-express
          - eventually-broker

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install
        run: yarn install

      - name: create .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc

      - name: config git
        run: |
          git config user.name $GIT_USERNAME
          git config user.email $GIT_USEREMAIL
          git remote set-url origin "https://${GIT_USERNAME}:${GITHUB_TOKEN}@${GIT_HOST}/${GIT_REPO}"

      - name: semrel analyze ${{ matrix.lib }}
        id: analyze

        env:
          PACKAGE: "@rotorsoft/${{ matrix.lib }}"
          DIRECTORY: "libs/${{ matrix.lib }}"
        run: |
          echo "::set-output name=semrel::$(npx zx ./scripts/semrel/analyze.mjs | tail -n -1)"

      - name: semrel release ${{ matrix.lib }}
        shell: sh
        run: |
          ::debug::{env.SEMREL}

          lastTag=${{ fromJSON(env.SEMREL.lastTag) }}
          nextTag=${{ fromJSON(env.SEMREL.nextTag) }}
          nextVersion=${{ fromJSON(env.SEMREL.nextVersion) }}
          releaseNotes=${{ fromJSON(env.SEMREL.releaseNotes) }}

          if [[ $lastTag == "${PACKAGE}*" ]]; then
            msg="chore(release): ${NEXT_TAG} [skip ci]"
            echo "${RELEASE_NOTES}\n $(cat ./CHANGELOG.md)" > ./CHANGELOG.md
            npm --no-git-tag-version version ${NEXT_VERSION} --workspace ${PACKAGE}
            git add -A .
            HUSKY=0 git commit -am ${msg}
            git tag -a ${NEXT_TAG} HEAD -m ${msg}
            HUSKY=0 git push --follow-tags origin HEAD:refs/heads/master

            data=$(jq -n \
              --arg tag "$NEXT_TAG" \
              --arg notes "$RELEASE_NOTES" \
              '{name: $tag, tag_name: $tag, body: $notes}')
            curl -u ${GIT_USERNAME}:${GITHUB_TOKEN} -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${GIT_REPO}/releases -d ${data}

            npm config set registry https://registry.npmjs.org
            yarn ${DIRECTORY} npm publish --access public
            echo "🚀 ${NEXT_TAG} released succesfully!"
          else
            echo "No semantic changes found!"
          fi
        env:
          npm_config_yes: true
          SEMREL: ${{ fromJSON(steps.analyze.outputs.semrel) }}
