name: CI-CD
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GIT_USERNAME: rotorsoft
  GIT_USEREMAIL: rotorsoft@outlook.com
  GIT_HOST: github.com
  GIT_REPO: rotorsoft/eventually-monorepo

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_PASSWORD: postgres
        # health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: build service
        run: yarn install && yarn build

      - name: unit test
        run: yarn test --coverage
        env:
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_DATABASE: postgres

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: create .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc

      - name: semantic release
        shell: sh
        run: |
          git config user.name ${GIT_USERNAME}
          git config user.email ${GIT_USEREMAIL}
          git remote set-url origin https://${GIT_USERNAME}:${GITHUB_TOKEN}@${GIT_HOST}/${GIT_REPO}

          libs=(eventually eventually-pg eventually-express eventually-broker)
          for lib in "${libs[@]}"
            do
              export PACKAGE=@rotorsoft/$lib
              export DIRECTORY=libs/$lib    
              
              echo "-----------------------------------------------------------------------------------------------------"
              echo ${PACKAGE}
              read -r lastTag nextTag nextVersion releaseNotes <<< $(npx zx ./scripts/semrel/analyze.mjs | tail -n -1 | jq '.lastTag,.nextTag,.nextVersion,.releaseNotes' | cut -d "\"" -f 2)
              if [[ ! $nextTag = "null" ]]; then
                export NEXT_TAG=$nextTag
                export NEXT_VERSION=$nextVersion
                export RELEASE_NOTES=$releaseNotes
                sh ./scripts/semrel/log-commit-tag.sh
                sh ./scripts/semrel/github-release.sh
                sh ./scripts/semrel/npm-publish.sh
              fi
              echo "-----------------------------------------------------------------------------------------------------"
              echo
            done
        env:
          npm_config_yes: true
