name: CI-CD
on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_PASSWORD: postgres
        # health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: yarn install
      - run: yarn build

      - name: run unit tests
        run: yarn test --coverage
        env:
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_DATABASE: postgres

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      #- name: semantic release
      #  run: yarn release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
